### PR TITLE
chore(docs): Move wiki content to the README #41

### LINKED ISSUE #41: Move wiki content to the README
https://github.com/ethereumjs/ethereumjs-blockchain/wiki/Accessing-ethereum-blockchain-object-methods by @shanawarkhan

### PR DESCRIPTION
**Pull request by js-kyle**
Fixes #41.

### CODE REVIEW

**Comment by holgerd77** [comment]
Thanks for the PR!

This is very much some generic "how to use a Node library standalone" instruction which we also didn't include in the other ``EthereumJS`` libs, since it's not contributing much to the specific lib documentation. So I wouldn't really want to merge this.

**Comment by js-kyle** [comment]
@holgerd77 Perhaps you could close this issue then? https://github.com/ethereumjs/ethereumjs-blockchain/issues/41

**Comment by holgerd77** [comment]
@js-kyle Ah, sorry, for that, didn't see that. Will reopen and leave to @axic to decide.

**Comment by axic** [comment]
Sorry @js-kyle, when we created the issue we haven't paid enough attention to the content of the wiki. The "some of the following useful methods will also be available for interacting with the blockchain" part looked more interesting, however it doesn't contain much detail.

**Pull request closed without merging**
