### PR TITLE
Add EditorConfig file

### PR DESCRIPTION
**Pull request by whymarrh**
This PR adds a simple EditorConfig file.

From the site:

> EditorConfig helps maintain consistent coding styles for multiple developers working on the same project across various editors and IDEs. The EditorConfig project consists of a **file format** for defining coding styles and a collection of **text editor plugins** that enable editors to read the file format and adhere to defined styles. EditorConfig files are easily readable and they work nicely with version control systems.

It is important to note that this is a language- and tooling-agnostic configuration that simply allows for a cross-editor set of configurations to be shared. A large number of editors (including GitHub's built-in editor here) support these settings. See also: [the list of editors and plugins](https://editorconfig.org/#download).

### CODE REVIEW

**Comment by holgerd77** [comment]
TBH I am a bit hesitant. Then we have yet another config file to maintain and update for 10-20 libraries, depending where we deploy. I also thought if this could be a candidate for [ethereumjs-config](https://github.com/ethereumjs/ethereumjs-config), but atm it seems not possible to extend ``editorconfig``, there is a currently open [discussion](https://github.com/editorconfig/editorconfig/issues/236) on that.

And formatting is also already enforced by usage of ``prettier``.

**Comment by whymarrh** [comment]
> And formatting is also already enforced by usage of `prettier`.

Yup, the EditorConfig setup is more for the humans using their editors where `prettier` can clean up any mistakes afterwards.

**Comment by holgerd77** [comment]
Hmm, I see that this is useful to some extend. The other argumentation line would be: people can work with their own whatever-they-like settings and do some ``prettier`` run at the end (realistically needed anyway since one is normally not staying in the code-style conventions on all places), once we have [Git hooks](https://github.com/ethereumjs/ethereumjs-config/issues/16) in place the problem of forgetting this is getting even smaller.

So, not sure, "if" then I would like to have stuff like this throughout the various libraries and not only randomly in one. @s1na, @danjm, @chikeichan what do you think?

Another way around (thinking in progress... 🚂 😄), along with the "Git Hooks" introduction we can also introduce this editor file without too much overhead. I also wanted to write together one issue and PR template heavily linking to the respective EthereumJS sections (contribution, tech standards,...), we can then do all three things together. Maybe I'll just take on this.

Nevertheless I would appreciate some more feedback on the editor config settings here.

**Comment by holgerd77** [comment]
@s1na @danjm @chikeichan can any/some of you give an opinion if this is desired or not? Then I would add this along the next organization wide update round (together with Git hooks + some issue/PR templates referencing the relevant organizational docs sections).

**Comment by s1na** [comment]
I don't have much to say. As you mentioned, `prettier` and linters can enforce a consistent codebase in the libraries and combining it with git hooks makes this process convenient. But on the other hand, if some people would rather have this in their editors I can understand that too (and would install the vim editorconfig plugin).

**Comment by chikeichan** [comment]
> @s1na @danjm @chikeichan can any/some of you give an opinion if this is desired or not? Then I would add this along the next organization wide update round (together with Git hooks + some issue/PR templates referencing the relevant organizational docs sections).

I typically do not include EditorConfig file in repo, and uses linter to enforce consistent styling. I also am not a big fan of git hooks, and found myself skipping them until my code is closer to be ready for PR.

**Comment by holgerd77** [comment]
Ok, then I'll leave out the editor file and close this hear since opinions are too mixed.

@chikeichan We only want to do one ``pre-push`` gitHook for linting/formatting, this normally doesn't run too long, so no automatic test runs or anything. And for linting it is really valuable since this disturbs workflow on 30-50% of PRs since everyone is forgetting it (especially new contributors).

**Pull request closed without merging**
