### PR TITLE
Add github actions

### LINKED ISSUE #133: Migrate ethereumjs-blockchain from Travis to Github Actions
As we've been [planning to move over to a monorepo](https://github.com/ethereumjs/ethereumjs-vm/issues/561), we can start by migrating their CIs to the same service.

### PR DESCRIPTION
**Pull request by ryanio**
Adds Github Actions workflows:

Node 8, 10, 12, 13: `test`
Node 12: `lint`, `coveralls`, `coverage`

You can see how the checks will look [here](https://github.com/ryanio/ethereumjs-blockchain/pull/4/checks).

I also put together a sample circleci config in another branch for comparison: [config.yml](https://app.circleci.com/github/ryanio/ethereumjs-blockchain/pipelines/9d550cf8-d7d3-486a-bc37-261ea03ca24e/config) and [result](https://app.circleci.com/github/ryanio/ethereumjs-blockchain/pipelines/9d550cf8-d7d3-486a-bc37-261ea03ca24e/workflows/e4e609ce-6f5b-4f6f-9263-598c7fd5d378).

---

Closes #133

### CODE REVIEW

**Comment by holgerd77** [comment]
This actually looks really nice (GitHub Actions reporting) and is a lot better integrated, wonder if we should switch here? Any thoughts @s1na @alcuadrado @evertonfraga?

**Comment by ryanio** [comment]
What are the differences between `tslint` and `lint`, should we run both on CI? Travis was just running `lint`.

How about `coverage` vs `coveralls` vs `nyc`? Travis was just running `coveralls`, but I could easily add all of them.

**Comment by evertonfraga** [comment]
`coveralls`: is a service to track and report coverage changes (notice the badge on repo readme)
`nyc`: [tool from istanbul](https://github.com/istanbuljs/nyc) that collects coverage while tests are run
`npm run coverage`: script that runs `nyc`

**Comment by evertonfraga** [comment]
Something that helps me quickly inspect all projects differences is to inspect their `scripts` section. Here's how you can print all of them:

```shell
cat ethereumjs-*/package.json | jq '{name: .name, script: .scripts}'
```

requires that each project preserves the `ethereumjs-` prefix in their directory names, and [jq](https://stedolan.github.io/jq/).

**Comment by evertonfraga** [comment]
@holgerd77 Definitely looks nicer, as it's more integrated and organized.

Ryan's idea and effort came in super handy, as I've been thinking about the CI strategy for cross-library tests and monorepo.

I will RTM and see if it compares to CircleCI in some specific aspects. I'll then assess if it's worth to drop the `workflows` (build tree) back to a flat job structure.

**Comment by alcuadrado** [comment]
This looks really good! Am I reading the results incorrectly, or are actions much faster than travis? travis jobs took about 3min, and actions ~1.

**Comment by ryanio** [comment]
> This looks really good! Am I reading the results incorrectly, or are actions much faster than travis? travis jobs took about 3min, and actions ~1.

It seems to be consistently that fast!

**Comment by holgerd77** [comment]
@ryanio The `tslint` command is running the linter together with the formatter (`prettier`), see scripts [here](https://github.com/ethereumjs/ethereumjs-config/tree/master/packages/ethereumjs-config-tslint/cli), I agree that it's a bit confusing combination and naming.

**Pull request closed without merging**
