### PR TITLE
Typedoc generated docs

### LINKED ISSUE #95: Auto-generated documentation with TSDocs
Documentation of this library should be auto-generated with `TypeDoc`, this PR https://github.com/ethereumjs/ethereumjs-util/pull/170 can serve as a reference (see also [technical docs on documentation](https://ethereumjs.readthedocs.io/en/latest/technical.html#documentation)).

For this the manual documentation comments in the `README` (https://github.com/ethereumjs/ethereumjs-account) should be integrated in the code along the way.

Only functionality in [index.ts](https://github.com/ethereumjs/ethereumjs-blockchain/blob/master/src/index.ts) is currently part of the external API and should be publicly exposed (so roughly the currently documented functions, apart from eventually some updates from recent changes or functionality additions).

### PR DESCRIPTION
**Pull request by alcuadrado**
This PR fixes #95, updating the docs to be compatible with the `ethereumjs-config` setup. 

It mostly moves the docs from the `README.md` to the sources, with some formatting changes. 

Note I didn't find places where the doc was outdated, but I'm not that familiar with this library yet, so I may have missed something.

Finally, I'm not sure how to document `Blockchain.prototype.db`, `Blockchain.prototype.dbManager`, and `Blockchain.prototype.ethash`. I suspect they should have been `private` fields. Apart from that, it is ready for review.

### CODE REVIEW

**Comment by alcuadrado** [comment]
Oops, my bad. I didn't realized that those new `private`s were actually changing the code, and not just docs.

Some tests broke because of this. They were using private APIs, so I'm not sure what's the best way to move forward.

The easiest way of fixing this is to make things `public` again, and ignore them with the `@hidden` tsdoc tag.

**Comment by alcuadrado** [comment]
> The easiest way of fixing this is to make things public again, and ignore them with the @hidden tsdoc tag.

I went ahead and implemented this to keep this PR small.

**Comment by holgerd77** [comment]
Some other notes:
- we should eventually extract the example again to the main readme, think this is more friendly and makes the library more approachable
- There is still Constantinople referenced as latest HF option in the constructor, this should be updated to Petersburg

**Comment by holgerd77** [comment]
(these can also be addressed later/separate)

**Pull request merged**
